### ISSUE TITLE
cant work in random file fivem script

### ISSUE THREAD

**Issue by xenfovn** [yunglean4171/discord-bot-lua-obfuscator#1]
not working on this file
[ok.txt](https://github.com/yunglean4171/discord-bot-lua-obfuscator/files/8601110/ok.txt)
 
 
![image](https://user-images.githubusercontent.com/55439243/166192315-a4cc7c27-fd51-45b8-9d1b-13f5a5adfc77.png)

bot not send output file

**Comment by yunglean4171** [comment]
> not working on this file
> [ok.txt](https://github.com/yunglean4171/discord-bot-lua-obfuscator/files/8601110/ok.txt)
>  
>  
> ![image](https://user-images.githubusercontent.com/55439243/166192315-a4cc7c27-fd51-45b8-9d1b-13f5a5adfc77.png)
> 
> bot not send output file

check if there is any error output in bot cmd

**Comment by 023948799e213e21b53eb83785356208** [comment]
Its not meant for fivem scripts.

**Comment by yunglean4171** [comment]
It is
