### ISSUE TITLE
Help please 

### ISSUE THREAD

**Issue by max2007killer** [yunglean4171/discord-bot-lua-obfuscator#10]
im send file bot not send [bot online]
![ff](https://user-images.githubusercontent.com/50517869/206872729-00372b0c-bafb-46e6-839d-0acbc943bb2b.png)

**Comment by max2007killer** [comment]
### 
![what1](https://user-images.githubusercontent.com/50517869/206886874-68cb51d5-8d15-4a59-bed7-38d70fa8d22b.png)
HELP

**Comment by TO4HOHEDAYH** [comment]
ку пупс, есть тема для обсуждения, по поводу бабфта.

**Comment by yunglean4171** [comment]
install lua interpreter: [download](https://www.lua.org/download.html)
