### ISSUE TITLE
bugs in obfuscate.lua

### ISSUE THREAD

**Issue by dambro1990** [yunglean4171/discord-bot-lua-obfuscator#15]
good evening I found 5 bugs in the obfuscate.lua file, I attach photos to help you understand better
![bugs_boot](https://user-images.githubusercontent.com/101954137/215223682-14abd157-6ae0-4f8f-a248-d0293abe7508.png)

**Comment by yunglean4171** [comment]
Hey I assure you that this warnings wont affect the operation of the obfusctaor.
If u want make an issue ticket at obfuscators og creator:
https://github.com/Direnta/LuaSeel/blob/master/obfuscator.lua
