### ISSUE TITLE
Fivem Script Error

### ISSUE THREAD

**Issue by benk1960** [yunglean4171/discord-bot-lua-obfuscator#2]
Error loading script server.lua in resource input: @input/server.lua:11: attempt to call a nil value (local 'IllIIllIIllIII')

![image](https://user-images.githubusercontent.com/44873773/172018522-3f82e4c9-7e18-40be-9d6c-609ce8089e38.png)

**Comment by yunglean4171** [comment]
prolly u have errors in ur og script
