### ISSUE TITLE
wth

### ISSUE THREAD

**Issue by anhtlauncher** [yunglean4171/discord-bot-lua-obfuscator#3]
![image](https://user-images.githubusercontent.com/99712037/189870875-f917477c-99fe-4c4b-a2f5-9f6aff989d30.png)
im new here so idk how to find please help, thanks.

**Comment by quanmanss11** [comment]
here https://luaobfuscator.com

**Comment by quanmanss11** [comment]
for https://vanilla-ac.com/obfuscator/

**Comment by quanmanss11** [comment]
https://onecompiler.com/lua/3wvx5uv9z (epic)
