### ISSUE TITLE
It does not work.

### ISSUE THREAD

**Issue by WavaAdrian** [yunglean4171/discord-bot-lua-obfuscator#4]
![image](https://user-images.githubusercontent.com/87927419/191816352-9b0a8cff-72a4-4d35-80f1-75b0674c26a2.png)

It does not come any output and there is no errors.

![image](https://user-images.githubusercontent.com/87927419/191816472-53689abc-0156-4442-9c48-08ec3f95d5a9.png)

**Comment by yunglean4171** [comment]
prolly u have to install lua interpreter

**Comment by WavaAdrian** [comment]
Sorry i found out how to fix it. It was because I did not have on MESSAGE CONTENT INTENT. Lol
![image](https://user-images.githubusercontent.com/87927419/195085940-c4c0f548-4805-43a9-8eb4-fb321a8357dc.png)
